[package]
name = "common"
version = "0.1.0"
authors = ["Yang Qi <y3tothe6@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.106", features = ["derive"] }
url = "2.1.1"
